###################################################
###################################################
# 
# Database & Redis services only
# 
###################################################
###################################################

version: "3.8"

networks:
  traefik-public:
    external: true

services:
  redis:
    image: redis:6.2.5
    restart: always
    ports:
      - 6379
    command: redis-server
    networks:
      - traefik-public
    labels:
      - "traefik.enable=false"

  db:
    image: mariadb:10.8.2-rc-focal
    restart: always
    environment:
      MARIADB_USER: wordpress_db
      MARIADB_PASSWORD: WBjAlX3veYGtSYg6
      MARIADB_ROOT_PASSWORD: WBjAlX3veYGtSYg5
      MARIADB_DATABASE: wordpress_db
    ports:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - traefik-public
    labels:
      - "traefik.enable=false"

volumes:
  mysql:
